sudo: required

services:
  - docker

before_install:
  - docker build -t alparslanozturk/docker-react -f Dockerfile.dev . 

script:
  - docker run alparslanozturk/docker-react npm run test -- --coverage